# Site settings
title: Fabrizio Goglia
#email: fabrizio.goglia@gmail.com
description: Process design collective based in Venice
baseurl: "http://fabriziogoglia.com/" # the subpath of your site, e.g. /blog/
url: "http://fabriziogoglia.com/" # the base hostname & protocol for your site
twitter_username: fabriziogoglia


# Build settings
markdown: kramdown
excerpt_separator: "\n\n"
